on:
  workflow_call:
    inputs:
      java-version:
        default: '21'
        required: false
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java-version }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -f pom.xml test
  release:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{steps.artifact-name.outputs.artifact_name}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java-version }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -f pom.xml package
      - id: artifact-name
        run: echo "artifact_name=$(ls -A ./target/*.jar)" >> "$GITHUB_OUTPUT"
      - name: Start Application
        run: java -jar ./target/*.jar