on:
  workflow_call:
    inputs:
      package-manager:
        description: 'Package Manager (Example: npm , maven, gradle)'
        required: false
        type: string
      java-version:
        default: '17'
        required: false
        type: string
      node-version:
        default: '20'
        required: false
        type: string
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm install -g bats
      - run: bats -v